version: '3'

services:

  web:
    build:
      context: .
      dockerfile: ./docker/dockerfile
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./www:/var/www
    ports:
      - 80:80
    depends_on:
    - db

  db:
    image: mysql:5.7
    volumes:
      - ./docker/db/mysql:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=root
    command: mysqld --sql_mode="" --character-set-server=utf8 --collation-server=utf8_slovenian_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0

  smtp:
      image: schickling/mailcatcher
      ports:
        - "1080:1080"
        - "1025:1025"