FROM centos:7
RUN yum update -y && yum clean all

# Repository
# EPEL
RUN yum install -y epel-release
# remi
RUN yum -y install http://rpms.famillecollet.com/enterprise/remi-release-7.rpm

# Install apache
RUN yum install -y httpd

# Install PHP
RUN yum -y install --enablerepo=remi,remi-php74 php php-pear php-devel php-mbstring php-pdo \
  php-xml php-gd php-fpm php-mysqlnd php-opcache php-pecl-zip libzip5 ImageMagick php-intl

# Mailcatcher
RUN yum -y install ruby ruby-devel
RUN yum -y install gcc-c++
RUN yum -y install sqlite-devel
RUN gem install mailcatcher

# Imagick
RUN yum -y install ImageMagick ImageMagick-devel \
 && pecl install imagick
RUN echo "extension=imagick.so" > /etc/php.d/imagick.ini

# apcu
RUN pecl install apcu
RUN echo "extension=apcu.so" > /etc/php.d/apcu.ini

# PHP
COPY ./docker/php/php.ini /etc/
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Apache
COPY ./docker/apache/base.conf /etc/httpd/conf.d/
RUN rm /etc/httpd/conf.d/welcome.conf
CMD ["/usr/sbin/httpd", "-DFOREGROUND"]